#!/bin/bash

set -e

# link dotfiles
ln -sfnv $(echo $(pwd)/.[^.]* | \
  xargs -n1 | \
  grep -v '\.config' |\
  grep -v '\.git$' | \
  grep -v '\.gnupg' |\
  xargs) ~

# link config
mkdir -p ~/.config
for dir in .config/*/; do
  ln -sfnv "$(pwd)/${dir%/}" ~/.config/
done

# scala - sbt
mkdir -p ~/.sbt/plugins
ln -svf $(pwd)/boot.sbt ~/.sbt/plugins

# link binaries
mkdir -p ~/bin
ln -sfv $(pwd)/bin/* ~/bin

# configure trackpad on linux
if uname -a | grep "^Linux" >/dev/null; then
  sudo cp 60-synaptics.conf /usr/share/X11/xorg.conf.d
fi

# services
rm -rf ~/service
cp -r service ~

echo
echo YO!
