#!/bin/sh

set -e
set -u

prefix=~/vim
vimsrc=$prefix/src

# get vim
mkdir -p $vimsrc
git clone https://github.com/vim/vim.git $vimsrc
cd $vimsrc
git pull

# build and install vim
./configure --prefix=$prefix \
            --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config \
            --enable-luainterp=yes

make && make install

# for ensime vim
pip install websocket-client sexpdata
