#!/bin/sh

# paths
echo setenv PATH /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin > /etc/launchd.conf

# default shell is zsh
chsh -s /bin/zsh

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# fix hostname
scutil --set LocalHostName przl
scutil --set HostName przl

# repeat rate
defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

# apps
brew tap caskroom/versions
brew cask install \
  1password \
  anaconda \
  atom \
  dash \
  docker \
  dropbox \
  googe-chrome \
  intellij-idea \
  iterm2 \ 
  java \
  java7 \
  julia \
  rstudio \
  skype \
  spotify \
  tunnelblick
