#!/bin/sh

set -e
set -u

# base
apt-get update -qq
apt-get -q -y install git zsh python-software-properties
add-apt-repository -y ppa:dotcloud/lxc-docker
apt-get update -qq
apt-get install -q -y lxc-docker

