#!/bin/sh
#
#

set -eou pipefail

# paths
# echo setenv PATH /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin > /etc/launchd.conf

# default shell is zsh
chsh -s /bin/zsh

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# fix hostname
scutil --set LocalHostName przl
scutil --set HostName przl

# repeat rate
defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

# apps
brew tap homebrew/cask-versions
brew install --cask \
  1password \
  anaconda \
  caffeine \
  dash \
  datagrip \
  docker \
  dropbox \
  google-chrome \
  iterm2 \
  julia \
  r \
  rstudio \
  slack \
  skype \
  spotify

brew tap MTG/essentia
brew install essentia

# spacemacs
brew tap d12frosted/emacs-plus
brew install emacs-plus --HEAD --with-natural-title-barsr
brew linkapps emacs-plus

