#!/bin/sh

set -e
set -u

prefix=~/vim
vimsrc=$prefix/src

# get vim
mkdir -p $vimsrc
git clone https://github.com/vim/vim.git $vimsrc
cd $vimsrc
git pull

# build and install vim
./configure --prefix=$prefix
make && make install
